name: TestFingerCoaster

on:
    push:
        branches: [ main ]

jobs: 
  buildRunTest: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: "Qt install"
        uses: jurplel/install-qt-action@v2
        
