name: "FingerCoaster:build-test"

on:
  push:
    branches: [master]

jobs: 
  build-test: 
    runs-on: ubuntu-latest
    steps: 
      - 
        instal-deps: "true"
        modules: qtnetwork
        name: InstallQt
        uses: jurplel/install-qt-action@v2
        version: "6.2.2"
