--- 
jobs: 
  build-test: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@master
      - 
        instal-deps: "true"
        modules: qtnetwork
        name: InstallQt
        uses: jurplel/install-qt-action@v2
        version: "6.2.2"
        with: ~
      - 
        name: createBuildDir
        run: "mkdir build"
      - 
        name: compile
        run: make
        working-directory: ./build
      - 
        name: runGame
        run: ./FingerCoaster
name: "FingerCoaster:build-test"
true: 
  push: 
    branches: 
      - master
