--- 
jobs: 
  build-test: 
    runs-on: ubuntu-latest
    steps: 
      - 
        instal-deps: "true"
        modules: qtnetwork
        name: InstallQt
        uses: jurplel/install-qt-action@v2
        version: "6.2.2"

name: "FingerCoaster:build-test"
true: 
  push: 
    branches: 
      - master
